from .learner import Learner, LearnerMAS
from .multi_agent_rl import (
    IAC_Learner,
    IPPO_Learner,
    MAPPO_Clip_Learner,
)

REGISTRY_Learners = {
    "BasicLearner": Learner,
    "BasicLearnerMAS": LearnerMAS,
    "IAC_Learner": IAC_Learner,
    "IPPO_Learner": IPPO_Learner,
    "MAPPO_Clip_Learner": MAPPO_Clip_Learner,
}

__all__ = [
    "REGISTRY_Learners",
    "Learner",
    "LearnerMAS",
    "PG_Learner",
    "A2C_Learner",
    "PPOCLIP_Learner",
    "PPOKL_Learner",
    "PPG_Learner",
    "DDPG_Learner",
    "TD3_Learner",
    "SAC_Learner",
    "SACDIS_Learner",
    "PDQN_Learner",
    "MPDQN_Learner",
    "SPDQN_Learner",
    "NPG_Learner",
    "DQN_Learner",
    "DuelDQN_Learner",
    "DDQN_Learner",
    "PerDQN_Learner",
    "C51_Learner",
    "QRDQN_Learner",
    "DRQN_Learner",
    "DreamerV2_Learner",
    "DreamerV3_Learner",
    "IQL_Learner",
    "VDN_Learner",
    "QMIX_Learner",
    "WQMIX_Learner",
    "QTRAN_Learner",
    "IAC_Learner",
    "VDAC_Learner",
    "COMA_Learner",
    "IPPO_Learner",
    "MAPPO_Clip_Learner",
    "MFQ_Learner",
    "MFAC_Learner",
    "IDDPG_Learner",
    "MADDPG_Learner",
    "MATD3_Learner",
    "ISAC_Learner",
    "ISACDIS_Learner",
    "MASAC_Learner",
    "MADDPG_Learner",
    "IC3Net_Learner",
    "CommNet_Learner",
    "TarMAC_Learner",
    "TD3_BC_Learner",
    "CURL_Learner",
    "SPR_Learner",
    "DrQ_Learner",
]
