from .core import (
    ActorNet,
    BasicQhead,
    CategoricalActorNet,
    CategoricalActorNet_SAC,
    CriticNet,
    GaussianActorNet,
    GaussianActorNet_SAC,
    QMIX_FF_mixer,
    QMIX_mixer,
    QTRAN_alt,
    QTRAN_base,
    VDN_mixer,
)
from .deterministic_marl import BasicQnetwork as BasicQnetwork_marl
from .deterministic_marl import (
    DCG_policy,
    Independent_DDPG_Policy,
    MADDPG_Policy,
    MATD3_Policy,
    MFQnetwork,
    MixingQnetwork,
    Qtran_MixingQnetwork,
    Weighted_MixingQnetwork,
)
from .gaussian_marl import Basic_ISAC_Policy as Gaussian_ISAC
from .gaussian_marl import MAAC_Policy as Gaussain_MAAC
from .gaussian_marl import MASAC_Policy as Gaussian_MASAC

Mixer = {"VDN": VDN_mixer, "QMIX": QMIX_mixer, "WQMIX": QMIX_FF_mixer, "QTRAN_alt": QTRAN_alt, "QTRAN_base": QTRAN_base}

REGISTRY_Policy = {
    # ↓ Multi-Agent DRL ↓ #
    "Basic_Q_network_marl": BasicQnetwork_marl,
    "Mixing_Q_network": MixingQnetwork,
    "Weighted_Mixing_Q_network": Weighted_MixingQnetwork,
    "Qtran_Mixing_Q_network": Qtran_MixingQnetwork,
    "DCG_Policy": DCG_policy,
    "Independent_DDPG_Policy": Independent_DDPG_Policy,
    "MADDPG_Policy": MADDPG_Policy,
    "MF_Q_network": MFQnetwork,
    "Gaussian_MAAC_Policy": Gaussain_MAAC,
    "Gaussian_ISAC_Policy": Gaussian_ISAC,
    "Gaussian_MASAC_Policy": Gaussian_MASAC,
    "MATD3_Policy": MATD3_Policy,
}

__all__ = [
    "REGISTRY_Policy",
    "Mixer",
    "ActorNet",
    "CategoricalActorNet",
    "CategoricalActorNet_SAC",
    "GaussianActorNet",
    "GaussianActorNet_SAC",
    "BasicQhead",
    "CriticNet",
    "GaussianActorNet_SAC",
    "VDN_mixer",
    "QMIX_mixer",
    "QMIX_FF_mixer",
    "QTRAN_base",
    "QTRAN_alt",
    "Categorical_AC_Policy",
    "Categorical_Actor_Policy",
    "Categorical_PPG_Policy",
    "Categorical_SAC_Policy",
    "Gaussian_AC_Policy",
    "Gaussian_Actor_Policy",
    "Gaussian_PPG_Policy",
    "Gaussian_SAC_Policy",
    "BasicQnetwork",
    "DuelQnetwork",
    "NoisyQnetwork",
    "C51Qnetwork",
    "QRDQN_Network",
    "DDPGPolicy",
    "TD3Policy",
    "PDQNPolicy",
    "MPDQNPolicy",
    "SPDQNPolicy",
    "DRQNPolicy",
    "BasicQnetwork_marl",
    "MFQnetwork",
    "MixingQnetwork",
    "Weighted_MixingQnetwork",
    "Qtran_MixingQnetwork",
    "DCG_policy",
    "Independent_DDPG_Policy",
    "MADDPG_Policy",
    "MATD3_Policy",
    "Categorical_MFAC_Policy",
    "COMA_Policy",
    "Categorical_MAAC_Policy",
    "Categorical_MAAC_Policy_Share",
    "IC3Net_Policy",
    "CommNet_Policy",
    "TarMAC_Policy",
    "Categorical_ISAC",
    "Categorical_MASAC",
    "Gaussian_ISAC",
    "Gaussian_MASAC",
    "Gaussain_MAAC",
    "DreamerV2Policy",
    "DreamerV3Policy",
]
