from .base import Agent, MARLAgents, RandomAgents
from .base.callback import BaseCallback
from .core import OffPolicyMARLAgents, OnPolicyMARLAgents
from .multi_agent_rl import IPPO_Agents, MAPPO_Agents

REGISTRY_Agents = {
    "RANDOM": RandomAgents,
    "IPPO": IPPO_Agents,
    "MAPPO": MAPPO_Agents,
}

__all__ = [
    "BaseCallback",
    "Agent",
    "MARLAgents",
    "RandomAgents",
    "OnPolicyAgent",
    "OffPolicyAgent",
    "OffPolicyMARLAgents",
    "OnPolicyMARLAgents",
    "REGISTRY_Agents",
    "PG_Agent",
    "A2C_Agent",
    "PPOCLIP_Agent",
    "PPOKL_Agent",
    "PPG_Agent",
    "DDPG_Agent",
    "TD3_Agent",
    "PDQN_Agent",
    "MPDQN_Agent",
    "SPDQN_Agent",
    "SAC_Agent",
    "DQN_Agent",
    "DuelDQN_Agent",
    "DDQN_Agent",
    "NoisyDQN_Agent",
    "C51_Agent",
    "QRDQN_Agent",
    "PerDQN_Agent",
    "DRQN_Agent",
    "NPG_Agent",
    "DreamerV2Agent",
    "DreamerV3Agent",
    "IQL_Agents",
    "VDN_Agents",
    "QMIX_Agents",
    "WQMIX_Agents",
    "QTRAN_Agents",
    "DCG_Agents",
    "IAC_Agents",
    "VDAC_Agents",
    "COMA_Agents",
    "IDDPG_Agents",
    "MADDPG_Agents",
    "IC3Net_Agents",
    "CommNet_Agents",
    "TarMAC_Agents",
    "MFQ_Agents",
    "MFAC_Agents",
    "IPPO_Agents",
    "MAPPO_Agents",
    "ISAC_Agents",
    "MASAC_Agents",
    "MATD3_Agents",
    "TD3_BC_Agent",
    "CURL_Agent",
    "SPR_Agent",
    "DrQ_Agent",
]
